sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5.1'
  - '5'
  - '4'
  - '4.2'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v3
  - iojs-v2
  - iojs-v1
before_install:
  - npm install -g grunt-cli
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
